### PR TITLE
ci: fix warnings and improve runtime

### LINKED ISSUE #197: Building tachyon py is failed on latest macOS
### Issue type

Bug

### OS platform and distribution

macOS Sonoma

### Current behavior?

https://github.com/kroma-network/tachyon/actions/runs/7169954768/job/19537222364?pr=196

### Expected Behavior?

Build and test should be successful.

### Standalone code or description to reproduce the issue

```shell
> cd tachyon/py/test
> bazel test --config macos_arm64  //...
ERROR: /private/var/tmp/_bazel_chokobole/78478a39924d7742b4385236af2bac37/external/kroma_network_tachyon/tachyon/base/mac/BUILD.bazel:21:21: in objc_library rule @@kroma_network_tachyon//tachyon/base/mac:mac_logging: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 61, column 52, in _objc_library_impl
        File "/virtual_builtins_bzl/common/objc/semantics.bzl", line 54, column 13, in _check_toolchain_supports_objc_compile
Error in fail: Compiling objc_library targets requires the Apple CC toolchain which can be found here: https://github.com/bazelbuild/apple_support#toolchain-setup
ERROR: /private/var/tmp/_bazel_chokobole/78478a39924d7742b4385236af2bac37/external/kroma_network_tachyon/tachyon/base/mac/BUILD.bazel:21:21: Analysis of target '@@kroma_network_tachyon//tachyon/base/mac:mac_logging' failed
ERROR: Analysis of target '//tachyon/math/elliptic_curves/short_weierstrass:short_weierstrass_unittests_unittests' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.080s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: No test targets were found, yet testing was requested
```

### PR DESCRIPTION
**Pull request by batzor**
# Description

This PR fixes unused variable warnings and improves CI runtime from ~50 minutes to ~30 minutes. Also, `exclusive` tag is introduced to cpu heavy tests to prevent timeouts from happening. 

Closes #197 since it's no longer reproducible.

### CODE REVIEW

**Comment by chokobole** [comment]
- https://github.com/kroma-network/tachyon/pull/498/commits/13e47cb67ae11fa4b1b689791d551ce7ad596e9b, I think the type/scope should changed to **refac(c/examples)**
- [fix(examples): add exclusive tag to cpu heavy tests](https://github.com/kroma-network/tachyon/pull/498/commits/b5b68ae5379373a4fc6edec6a801781dc72dd8f2) should be changed to **build** without scope

**Review by chokobole — APPROVED** [review]
LGTM

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by ashjeong — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by GideokKim — APPROVED** [review]
LGTM

**Pull request merged**
