### PR TITLE
refac(base): separate iterator from adapters

### PR DESCRIPTION
**Pull request by chokobole**
# Description

I wrote this codes in Devconnect to create `Iterator` class to help us to take rust codes in c++ easily. But i couldn't finish it completely so this is a code change that is part of that purpose. You can think of it as a preparation for that.

### CODE REVIEW

**Comment by dongchangYoo** [comment]
There is a typo in second commit msg.
ChunkcedIterator -> ChunkedIterator

**Comment by dongchangYoo** [comment]
else, LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Pull request merged**
