### PR TITLE
feat: prepare gen vkey

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR implements things that are needed to generate verification key.

### CODE REVIEW

**Comment by dongchangYoo** [comment]
Please check the commit message of the first commit. (A typo was fixed in that commit!)

**Comment by dongchangYoo** [comment]
How about merging after [PR143](https://github.com/kroma-network/tachyon/pull/143) has been merged?
FYI, once PR143 is merged, you can obtain DensePoly, Eval, and Domain from PCSTy.

**Review by Insun35 — APPROVED** [review]
LGTM

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Pull request merged**
