### PR TITLE
feat(zk): implement auxiliary classes related to permutation

### PR DESCRIPTION
**Pull request by dongchangYoo**
This PR implements `Open()` and `Evaluate()` functions of  classes related to permutation.

- [evaluate()](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/permutation/prover.rs#L231-L276)
- [open()](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/permutation/prover.rs#L278-L324)

### CODE REVIEW

**Comment by dongchangYoo** [comment]
it must be merged after https://github.com/kroma-network/tachyon/pull/164

**Review by chokobole — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
Else, LGTM

**Pull request merged**
