### PR TITLE
build: use ffiasm to produce x86 assembly of prime fields

### PR DESCRIPTION
**Pull request by chokobole**
# Description

Previously, we utilized https://github.com/0xPolygonHermez/zkevm-prover/tree/main/src/ffiasm, which is why we named the flag polygon_zkevm_backend. However, this approach had limitations, as it only provided x86 assembly versions of `bn254` and `secp256k1`. Now, we have the original version of https://github.com/iden3/ffiasm, which generates x86 assembly for arbitrary prime fields as well as ARM assembly. However, the ARM version is still under development.

BREAKING CHANGE: The `polygon_zkevm_backend` flag is removed, and all prime fields now utilize x86 assembly.

### CODE REVIEW

**Comment by chokobole** [comment]
Please rename `benchmark.md` to `README.md` so that we can see the docs immediately as we navigate to the directory on the web.

**Comment by chokobole** [comment]
Please format the table with `markdown.extension.tableFormatter.enabled` on. Please refere to https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one.

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Review by ashjeong — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Pull request merged**
