### PR TITLE
ci: reduce cache storage usage

### PR DESCRIPTION
**Pull request by batzor**
# Description

GitHub cache storage is limited to 10GB but it looks like [we can exceed it easily](https://github.com/kroma-network/tachyon/actions/caches) when working on multiple branches.
Exceeding the storage limit may result in unwanted deletion of caches (i.e main branch caches). It even went up to 20GB+ at some point so I had to clean them up with a script. So with this PR, we try to minimize our cache storage usage while keeping build/test time low.

### CODE REVIEW

**Comment by batzor** [comment]
I tried to test the "branch cache deletion on merge" on my forked repo but [CI is still pending](https://github.com/batzor/tachyon/actions/runs/10176201982/job/28145059600). Please let me know if you have any idea for testing this feature.

**Review by chokobole — APPROVED** [review]
LGTM

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Comment by GideokKim** [comment]
LGTM

**Review by ashjeong — APPROVED** [review]
LGTM

**Review by GideokKim — APPROVED** [review]

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Pull request merged**
