### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ahmetgul23**
# Description

### CODE REVIEW

**Comment by ahmetgul23** [comment]
dsf

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Comment by TomTaehoonKim** [comment]
@ahmetgul23 The empty line there is on purpose. As you can see throughout the README, this change will harm consistency within the file. Sorry for approving by mistake. This PR will be closed soon.

**Comment by chokobole** [comment]
Close this issue since this PR tries to remove blank line but it doesn't conform to the styles that is used in other places.

**Pull request closed without merging**
