### PR TITLE
feat(zk): fill `transcript_repr` of `VerifyingKey`

### PR DESCRIPTION
**Pull request by dongchangYoo**
This PR implements [PinnedVerifyingKey](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk.rs#L256-L263). 
`PinnedVerifyingKey` can generate a string of `VerifyingKey` with only selective members.

And `transcript_repr` of the `VerifyingKey` is assigned a field element generated with a hash value of string of `PinnedVerifyingKey`.

### CODE REVIEW

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by chokobole — APPROVED** [review]
LGTM

**Comment by dongchangYoo** [comment]
You've done a great job! @chokobole 
And LGTM.

**Pull request merged**
