### PR TITLE
fix(c): activate gwc prover

### PR DESCRIPTION
**Pull request by dongchangYoo**
This PR enables the `GWCProver` C API.

### CODE REVIEW

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by ashjeong — APPROVED** [review]
LGTM

**Comment by chokobole** [comment]
Please change scope `c` to `c/zk`

**Comment by chokobole** [comment]
https://github.com/kroma-network/tachyon/pull/337/commits/08fbe26c1f234101320eb9fad5070387cb70cbdf and https://github.com/kroma-network/tachyon/pull/337/commits/d019c1ea42ca790aa0606e168fe55da6538e83d3 please fix type `fix` to `test`.

https://github.com/kroma-network/tachyon/pull/337/commits/b6068097d33908bf8a905bce951fe09afa2b8824 please fix type `fix` to `feat`.

**Review by chokobole — APPROVED** [review]
LGTM

**Pull request merged**
