### PR TITLE
feat: add initial template two adic fri pcs

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR initially adds simple SP1 code to Tachyon to test SP1 Prover with Tachyon.

### CODE REVIEW

**Comment by TomTaehoonKim** [comment]
@chokobole Could you add the reference in the commit message for the code in 912ddbd?

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by ashjeong — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Pull request merged**
