### PR TITLE
refac: rename group internal operations

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR renames some group operations after the internal discussion.

- `DoDoubleXXX()` to `DoubleImplXXX()`
- `DoSquareXXX()` to `SquareImplXXX()`
- `Negative()` to `Negate()`
- `NegInPlace()` to `NegateInPlace()`

### CODE REVIEW

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by ashjeong — COMMENTED** [review]
https://github.com/kroma-network/tachyon/pull/391/commits/0c888451b0c994c064f2b8cbdf53f71e4d6511f2
We decided to use full name for the unary operations.
->
We decided to use **the** full name for unary operations.

https://github.com/kroma-network/tachyon/pull/391/commits/948147290c5cf293a8976c63981404aeae6fee7c
I think you missed `rational_field.h`

https://github.com/kroma-network/tachyon/pull/391/commits/948147290c5cf293a8976c63981404aeae6fee7c & https://github.com/kroma-network/tachyon/pull/391/commits/6d51eaafab6b0073ebd01838a2396cb1c6bb9265
This **is for the** consistency with other **operation** that **has** `DoXXX` as
a private method.
->
This **keeps consistency** with other **operations** that **have** `DoXXX` as
a private method.

**Comment by ashjeong** [comment]
> [0c88845](https://github.com/kroma-network/tachyon/commit/0c888451b0c994c064f2b8cbdf53f71e4d6511f2) We decided to use full name for the unary operations. -> We decided to use **the** full name for unary operations.
> 
> [9481472](https://github.com/kroma-network/tachyon/commit/948147290c5cf293a8976c63981404aeae6fee7c) I think you missed `rational_field.h`
> 
> [9481472](https://github.com/kroma-network/tachyon/commit/948147290c5cf293a8976c63981404aeae6fee7c) & [6d51eaa](https://github.com/kroma-network/tachyon/commit/6d51eaafab6b0073ebd01838a2396cb1c6bb9265) This **is for the** consistency with other **operation** that **has** `DoXXX` as a private method. -> This **keeps consistency** with other **operations** that **have** `DoXXX` as a private method.

I realized I missed the same error for https://github.com/kroma-network/tachyon/pull/391/commits/f65dd0b34ec329121feca2b5e1aeac081376b670
use full name for the unary operations. -> We decided to use **the** full name for unary operations.

**Pull request merged**
