### PR TITLE
perf: optimize minor codes

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR optimizes codes a little bit.

### CODE REVIEW

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Comment by TomTaehoonKim** [comment]
@chokobole Isn't unbounded array -> fixed size array correct for [952a373](https://github.com/kroma-network/tachyon/pull/219/commits/952a37353f442863514abd21dab6d65e4f72b34e)'s commit message?

**Comment by chokobole** [comment]
> @chokobole Isn't unbounded array -> fixed size array correct for [952a373](https://github.com/kroma-network/tachyon/pull/219/commits/952a37353f442863514abd21dab6d65e4f72b34e)'s commit message?

I corrected it to `bounded_array`!

```c++
#include <iostream>
#include <type_traits>

int main() {
  int arr[] = {1, 2, 3};
  std::cout << std::is_bounded_array_v<decltype(arr)> << std::endl; // this prints 1
  return 0;
}
```

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Pull request merged**
