### PR TITLE
docs: update tachyon vs halo2 benchmarking results

### PR DESCRIPTION
**Pull request by ashjeong**
Benchmarking results are updated with Tachyon @ commit 2c6c4c47a0fe249dbefc20eeaa75127197b7dedc

### CODE REVIEW

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Comment by chokobole** [comment]
How do you think changing filename to `README.md`, so that people can see this when they navigate to `tachyon/zk/plonk/halo2`?

**Review by Insun35 — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Pull request merged**
