### PR TITLE
docs: fix circuit testing doc

### PR DESCRIPTION
**Pull request by ashjeong**
This PR fixes typos, changes variable names, and updates the `tracking_testing.md` doc for example circuit testing.

### CODE REVIEW

**Comment by chokobole** [comment]
- https://github.com/kroma-network/tachyon/pull/487/commits/951dbd3a46567e6f14ec0bee39f5da79530a87d7 should be typed with `test`.

**Review by TomTaehoonKim — APPROVED** [review]
> LGTM

**Review by chokobole — APPROVED** [review]
LGTM

**Review by GideokKim — APPROVED** [review]
LGTM

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by batzor — APPROVED** [review]
LGTM

**Pull request merged**
