### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by simlecode**
Fixes spelling typos in comments and docs

### CODE REVIEW

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGMT

**Review by chokobole — APPROVED** [review]
Thanks for your contribution! 🎉

If you want to keep contributing to our repository, please join https://t.me/zktachyon!

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by ashjeong — APPROVED** [review]
LGTM!

**Pull request merged**
