### PR TITLE
perf: optimize opening

### PR DESCRIPTION
**Pull request by chokobole**
# Description

Initially, we aimed to save memory by avoiding duplicated points. This led us to introduce the `PointSet` class to check for the existence of elements. However, the duration for the opening is not significant, and the size is not substantial, so optimizing for memory is not worthwhile. Instead, the focus should be on reducing the time when reviewing the benchmark results.

### CODE REVIEW

**Review by Insun35 — COMMENTED** [review]
Please fix typo in commit message of e9395a3: intermedidate -> intermediate

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Comment by ashjeong** [comment]
https://github.com/kroma-network/tachyon/pull/334/commits/816cbfcefcacc81f47e2c8e21e156fcfacb932cc
fix to be same as pr description (aka PointSet is properly enclosed by only one "`")

**Review by ashjeong — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Pull request merged**
