### PR TITLE
perf: add optimization flags

### PR DESCRIPTION
**Pull request by batzor**
# Description

In this PR, we add some compiler flags for improved performance at the cost of portability.

### CODE REVIEW

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by ashjeong — APPROVED** [review]
LGTM! Reducing the total flags the user needs to include on their own is great 🤌

**Review by GideokKim — APPROVED** [review]
LGTM

**Review by chokobole — APPROVED** [review]
LGTM

**Pull request merged**
