### PR TITLE
docs: run markdown linter

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR runs markdown linter.

### CODE REVIEW

**Review by ashjeong — APPROVED** [review]
LGTM

**Review by TomTaehoonKim — APPROVED** [review]
LGTM. Maybe later, we should add a doc with list of extensions recommended for VSCode users when trying to contribute to Tachyon.

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Comment by chokobole** [comment]
> LGTM. Maybe later, we should add a doc with list of extensions recommended for VSCode users when trying to contribute to Tachyon.

Very good idea!

**Pull request merged**
