### PR TITLE
feat: apply xor shift c api to rust binding

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR creates `XORShift` c api and applies this to rust binding.

### CODE REVIEW

**Review by Insun35 — COMMENTED** [review]
I think the commit bd10074 belongs to PR #258.

**Comment by chokobole** [comment]
> I think the commit [bd10074](https://github.com/kroma-network/tachyon/commit/bd100749b6ded2f40e9f91525cb6d7106b8b4c48) belongs to PR #258.

Yeap! This would be good to be merged after #258

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Pull request merged**
