### PR TITLE
feat: implement `Halo2RandomFieldGenerator`

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR implements `Halo2RandomFieldGenerator` based on https://github.com/kroma-network/tachyon/pull/151

### CODE REVIEW

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Review by Insun35 — APPROVED** [review]
LGTM

**Comment by chokobole** [comment]
I just added a comment about what I faced and how I overcame the issue during this PR.

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Pull request merged**
