### PR TITLE
fix(math): add missing changes from #388

### PR DESCRIPTION
**Pull request by chokobole**
# Description

This PR addresses the compilation error that occurred in #388.

### CODE REVIEW

**Review by ashjeong — COMMENTED** [review]
Should the same functions in `prime_field_gpu_debug.h` also be changed?

**Review by Insun35 — APPROVED** [review]
LGTM

**Comment by chokobole** [comment]
> Should the same functions in `prime_field_gpu_debug.h` also be changed?

Yes, since this is not used anywhere, so I didn't notice that! Thanks :)

**Review by TomTaehoonKim — APPROVED** [review]
LGTM

**Comment by TomTaehoonKim** [comment]
I just thought of it, maybe we should've added test cases for #388 where `std::nullopt` is returned when a malformed input is given. Perhaps this is too trivial?

**Comment by chokobole** [comment]
> I just thought of it, maybe we should've added test cases for #388 where `std::nullopt` is returned when a malformed input is given. Perhaps this is too trivial?

I added it!

**Review by Insun35 — APPROVED** [review]
LGTM

**Comment by chokobole** [comment]
> Should the same functions in `prime_field_gpu_debug.h` also be changed?

I changed it!

**Pull request merged**
